### ISSUE TITLE
Move ghost data

### ISSUE THREAD

**Issue by JarnoVgr** [JarnoVgr/Mr.Green-MTA-Resources#1]
Move ghost data out of resources folder.

**Comment by EsDeKa** [comment]
Where would you move it then? SQL or with the maps themselves?

**Comment by JarnoVgr** [comment]
Isn't there a possibility for separate data-storage for a MTA servers?

**Comment by EsDeKa** [comment]
MTA only supports files inside resources

I found a module that allows access to the whole filesystem though
https://wiki.multitheftauto.com/wiki/Modules/FileSystem

**Comment by JarnoVgr** [comment]
Relying on a custom module for this isn't a good idea, I think. Maybe it's better to make a 'data' folder in the resource to keep the resource-files & data files separated.
