### ISSUE TITLE
Converting all horns to mp3 + volume normalization

### ISSUE THREAD

**Issue by AleksCore** [JarnoVgr/Mr.Green-MTA-Resources#107]
Megas and Wes tried to convert all horns to mp3 and make the same volume for all horns. 

Here you can see what they got: http://bbq.to/playlist_346778_288152_40242(1)_7e84.zip

My thoughts about this:
- this horns sounds 30-40% quiter than originals which is bad
- this horns ~20MB - original ~15MB
- some horns obviously would sound different (worse). I am lazy to listen and compare 200 horns (~16 minutes).
- some of them could be even corrupted because converters not always convert correctly
- if we'll want to upload new horn - we'll need to convert/normalise every new horn

Based on the above - I say no.

But it's my opinion, let's hear another opinions down here.

**Comment by EsDeKa** [comment]
Increasing size? Not interested
