### ISSUE TITLE
Fixed horns volume, format, lower size.

### ISSUE THREAD

**Issue by Megas97** [JarnoVgr/Mr.Green-MTA-Resources#108]
Converted all 201 horns to .mp3 medium quality (44100hz, 128kbps, 100db vol). Size atm is 15.1MB and converted it's 14.7MB. I haven't listened to all tho. http://bbq.to/HORNS_1b12.zip
Some guys will say "shit quality", do horns really gotta be 320kbps super crisp sound? Isn't it enough for them to be understandable and just OK, not CD quality? :)

PS: I don't mind converting new horns and sending to F1MADKILLER! or AleksCore to replace old ones.

**Comment by AleksCore** [comment]
One does not simply change horns volume and don't <del>fuck them up</del> corrupt them :)

Current horns sounds nearly the same. +-10% difference isn't that big <del>to fuck with</del>. I am quickly listened 125 horns and they all sound the same. Maybe you'll find two or three that sound silent, but it isn't a reason to <del>fuck up</del> corrupt all horns.

And also what is 100db, max digital volume is 0db.

:)

**Comment by AfuSensi** [comment]
They sound alright, most are alot higher in volume.
Did you find any corrupted files aleks, i didnt.

If it aint corrupted then im all for replacing it to get some normalization with horn volumes. But we gotta think about future horns too, maybe megas wants to show how he did it for future horn uploaders?

**Comment by f1madkiller** [comment]
Wes is working on doing a .wav format for us and loudning the quiter 1s without breaking quality

**Comment by AfuSensi** [comment]
We dont need .wav, .wav is a lossy so its too big. Horns need to be compressed, so mp3 is the best option,

**Comment by AleksCore** [comment]
But they all upconverted to 44hz and 128kbits :| Nobody convert 22hz 64 kbit to 44hz 128kbit

**Comment by AleksCore** [comment]
And yea this last horns sounds not bad I think

**Comment by Megas97** [comment]
I can make a tutorial about how I did it but nobody can guarantee that users will use it though.

**Comment by AfuSensi** [comment]
Not all are 64kbps, but 64kbps is very bad in the first place.
Just listen to those, they are horrible.

**Comment by Megas97** [comment]
What do you mean, all are 128kbps :O

**Comment by AfuSensi** [comment]
The old ones.

**Comment by AleksCore** [comment]
You can't make horn sound better by converting from 64 kbits to 128 kbits

**Comment by Megas97** [comment]
True but size is smaller so who cares if even the 64kbps ones are 128kbps now

**Comment by AfuSensi** [comment]
My point is, whats the harm in going up from 64 to 128. I ment 64 shouldnt be uploaded in the first place in my opinion.

**Comment by AleksCore** [comment]
Yes so we talking about different things as always

**Comment by AleksCore** [comment]
You don't convert 400x400 image to 2000x2000. That's what I am talking about. But maybe for music it's ok

**Comment by AfuSensi** [comment]
It is very different, you wont notice a difference if 64 is converted to 128, and for consisency it would be good to do that, and keep doing that with new uploads.

**Comment by Megas97** [comment]
I get what you mean, the image would just look blurry and shit, but i don't think that with audio it's the same. If song has max 64kbps, then it doesn't matter if I make it 320kbps. It will sound always the same. Atleast that's how I understand it :D

**Comment by AleksCore** [comment]
Yes but what about size. Size will be different :)

**Comment by AfuSensi** [comment]
Dude its just a few ones that are 64, there is no problem here.

**Comment by Megas97** [comment]
Yes, and if users follow my yet unwritten tutorial, all will be fine ;)

**Comment by AleksCore** [comment]
no, leave converting and uploading for admins better :D

**Comment by AleksCore** [comment]
If you say it's ok - then it's ok. I am just about to include my 50 cents

**Comment by AfuSensi** [comment]
I understand what you mean aleks, but that would be a problem if we had 1000s of horns in 64 converted to 128, it doubles in size, but since there isnt alot of them, its not worth it going trough every file for it.

**Comment by AleksCore** [comment]
Alright :)

**Comment by Megas97** [comment]
So you need tutorial or I'm the new converter guy ;D?

**Comment by f1madkiller** [comment]
Tut be better

**Comment by Megas97** [comment]
http://mrgreengaming.com/forums/topic/17519-normalize-horns-tutorial-for-same-volume-only-for-mp3-files/

**Comment by f1madkiller** [comment]
Close this megas if u like now
