### ISSUE TITLE
CTF not working and error in rtf

### ISSUE THREAD

**Issue by Flipper123** [JarnoVgr/Mr.Green-MTA-Resources#125]
every time ctf comes, it cant start, just changes to random, it just adds 2nrg spawnpoints, and they are not registerd to any team and it skips ctf everytime, and in rtf if u change ur spawnpoint positon, u spawn outside map, in my case straight in watter

![mta-screen_2016-02-02_14-05-00] (https://cloud.githubusercontent.com/assets/16647544/12750615/8529afc4-c9b8-11e5-98ec-a0fb7fbc7735.png)

![mta-screen_2016-02-02_14-23-11](https://cloud.githubusercontent.com/assets/16647544/12750626/9e51f9f2-c9b8-11e5-8743-043e0e7d7d2b.png)

**Comment by f1madkiller** [comment]
this is a big bug

**Comment by EsDeKa** [comment]
my duel update broke it, so i stopped it untill fix
im in bed so idk when
