### ISSUE TITLE
Delay in markers

### ISSUE THREAD

**Issue by Flipper123** [JarnoVgr/Mr.Green-MTA-Resources#161]
Aleks can u make less delay time, because how it is atm, when u play  u pass 2 marker spots and ur delay still isnt completed

**Comment by EsDeKa** [comment]
Should be 5 seconds I think, how long is it now?

**Comment by Flipper123** [comment]
i think it is 5 seconds now, can it be less than 5 seconds?

**Comment by EsDeKa** [comment]
I think it's fine now, don't think you need to be able to have multiple pickups in 5 secs

Maybe a bit lower, 4 or 4.5 secs, but that's Aleks' decision

**Comment by Flipper123** [comment]
ok

**Comment by AleksCore** [comment]
Reduced to 4 from 5.5
