### ISSUE TITLE
Kills not shown

### ISSUE THREAD

**Issue by Flipper123** [JarnoVgr/Mr.Green-MTA-Resources#172]
so in SH kills are not shown in tab any more, is it bugged or removed? I am using old radar and old hud because of fps, sp i cant see kills anymore in SH

http://i.imgur.com/ipbiDIi.png

**Comment by AleksCore** [comment]
I noticed it isn't work in SH or in CarGame and removed it, because it isn't work so it's senseless to show it. Is it worked? In cargame there is levels which is almost the same as kills

**Comment by Flipper123** [comment]
but kill counter in SH was working

**Comment by AleksCore** [comment]
Just tested. Kill counter worked in SH in past but don't worked in CarGame mode. I will fix normal SH when I'll have time

**Comment by AleksCore** [comment]
For CarGame kills don't needed I guess 'cause there is Level.

**Comment by AleksCore** [comment]
81c44c684becd5a89f5fc38dbbecc6ebcfc429f9
