### ISSUE TITLE
[Suggestion] Make PM in F3 available when player's muted.

### ISSUE THREAD

**Issue by Megas97** [JarnoVgr/Mr.Green-MTA-Resources#174]
Right now if you're muted, you can still recieve PMs but you can't send any. Why not make it so that muted people can still not use chat (ofc) but be able to PM with a friend in F3?

**Comment by EsDeKa** [comment]
F3 was disabled during mute because muted players would use it in retaliation and secretly start spamming others.

If someone really wants to talk to a friend, they can use Skype/Steam
