### ISSUE TITLE
Mutes

### ISSUE THREAD

**Issue by f1madkiller** [JarnoVgr/Mr.Green-MTA-Resources#175]
There is a issue with mutes for what ever legth we mute a player for e.g. 24hrs they reconnect it comes on they are muted for 30 days @AleksCore fix!

**Comment by AleksCore** [comment]
I don't know. It works good here

**Comment by AleksCore** [comment]
Ok found the problem, fixing

**Comment by AleksCore** [comment]
9d71a506907fbc44172bab1b3c65c4081a387636 possibly fixed

**Comment by Megas97** [comment]
"possibly" not fixed. Still says 26 days..

**Comment by AleksCore** [comment]
@Megas97 there is no bugs as far as I see. The only bug is MadKiller

**Comment by Megas97** [comment]
So what now? It says 26 days still.

**Comment by AleksCore** [comment]
@Megas97 this questions not to me as I not muted you, so I can't unmute you or do something anyways

**Comment by AleksCore** [comment]
Would be nice to have any proofs of this bug and how to reproduce it. I can't fix fictional bug

**Comment by AleksCore** [comment]
I still think there was no any bugs related to mute length. There was missing logs for mute from admin panel and second bug -  "muted JohnDoe by JohnDoe's account". 

Couldn't reproduce the bug. Somebody abused mutes (pointing at @f1madkiller).
