### ISSUE TITLE
GC system

### ISSUE THREAD

**Issue by TheRetard** [JarnoVgr/Mr.Green-MTA-Resources#182]
Hello, I really wanted to help, because I need to know if it is possible to configure the GC in the mta system without the use of a MySQL server and if someone could explain to me how to do it.
 
I appreciate the opportunity and ask forgiveness for my lack of knowledge

**Comment by EsDeKa** [comment]
explanation for no gc accounts is here
https://github.com/JarnoVgr/Mr.Green-MTA-Resources/blob/master/README.md#setting-up-a-local-server

**Comment by TheRetard** [comment]
is it possible to use the GC system with the MTA's native registry system?
 /register /login

**Comment by EsDeKa** [comment]
no

**Comment by TheRetard** [comment]
I have one more doubt ...
I need to create the SQL tables in own mta server in some folder specifies?

**Comment by EsDeKa** [comment]
We use mysql for our sql tables

On my pc I use http://www.wampserver.com/en/, open phpmyadmin to create the SQL tables

**Comment by TheRetard** [comment]
Can I use the ones already are ready the mrgreen?

[]https://github.com/JarnoVgr/Mr.Green-MTA-Resources/tree/master/config(url)

**Comment by EsDeKa** [comment]
You need a seperate SQL server

Are you new to SQL? Because you need to learn a bit before you can use it

**Comment by TheRetard** [comment]
yes, ok
