### ISSUE TITLE
CoreMarkers 2nd bug

### ISSUE THREAD

**Issue by Megas97** [JarnoVgr/Mr.Green-MTA-Resources#193]
When someone slows me down, you know how the screen has those blue-ish stripes? Well, they never go away after that until map restarts or other one starts :)

**Comment by AleksCore** [comment]
Thanks, didn't tested it. And what's 1st bug? :)

**Comment by Megas97** [comment]
Yep, I thought it's nitro bug. Happens only after markers map comes so makes sense but dunno.

**Comment by AleksCore** [comment]
Alright, I'll remove coremarkers today, but later. So we will know exactly

**Comment by AleksCore** [comment]
@Megas97 Is it still happens?

**Comment by AleksCore** [comment]
Oh wait, stupid question. Coremarkers disabled currently. Anyways it should be fixed -> close.
