### ISSUE TITLE
Disable ability to play mix and race at the same time using the same account 

### ISSUE THREAD

**Issue by AleksCore** [JarnoVgr/Mr.Green-MTA-Resources#195]

**Comment by f1madkiller** [comment]
I thought SDK put a stop too this once?

**Comment by AleksCore** [comment]
I don't know @f1madkiller 

Can't check right now

**Comment by AleksCore** [comment]
Players who play only mix server come to race server and ask for their accounts to play only mix for double-gc

**Comment by JarnoVgr** [comment]
It should either block the login when the account is already in-use, or it should sign-out at the 'first' location.

**Comment by f1madkiller** [comment]
@AleksCore this can be fixed now as it is done i tested it otherday on my pc and laptop it logs out the account signed in first

**Comment by EsDeKa** [comment]
Like mad says I added the 'sign-out at first location' method a long time ago, if something is wrong let us know
