### ISSUE TITLE
Add country flags to the toptimes

### ISSUE THREAD

**Issue by AleksCore** [JarnoVgr/Mr.Green-MTA-Resources#197]
I hope Mr. SDK would help with this once he'll get a free time, since toptimes it's his script and I have no idea how it works.

**Comment by Megas97** [comment]
Robson. may be able to help with this. He did it for CrF (rip) server.

**Comment by AleksCore** [comment]
@Megas97 yeah, but he did it with another toptimes (not SDK-toptimes) and without MySQL shit

**Comment by AleksCore** [comment]
Fuck, I'll do it. Challenge accepted
