### ISSUE TITLE
Countdown misplaced on 2560x1440

### ISSUE THREAD

**Issue by JarnoVgr** [JarnoVgr/Mr.Green-MTA-Resources#210]
I play the game on 2560x1440 and the countdown is broken due to misplacement. Happens on all 4 countdown instances.

![gta_sa 2016-08-23 11-12-24-54](https://cloud.githubusercontent.com/assets/2751672/17887685/e6669d6a-6927-11e6-9440-418356edbaf4.png)

**Comment by AleksCore** [comment]
Pretty sure it's fixed now. If it isn't - reopen this issue
