### ISSUE TITLE
/whowas

### ISSUE THREAD

**Issue by f1madkiller** [JarnoVgr/Mr.Green-MTA-Resources#217]
/whowas can't find names like BtV|Flipper or SDK even this is quite important when trying to find blocker serials or those who broken rules as the script needs a colorcode if we could modify it to not need a colorcode to find the name it be good

**Comment by AleksCore** [comment]
Can't say much about this yet. It's hardcoded (default) command. It means I can't even edit this command, only disable. It's like /quit command. Hope you got it. I'll look what I can do when I'll get time for this
