### ISSUE TITLE
Random DD Stuff: "Teleport everyone's back"

### ISSUE THREAD

**Issue by AleksCore** [JarnoVgr/Mr.Green-MTA-Resources#222]
Probably bugged, need to check

**Comment by f1madkiller** [comment]
seems fine it teleports players back to where they where just before the vote

**Comment by f1madkiller** [comment]
@AleksCore you can close this as last time i was in mix it was fine

**Comment by AleksCore** [comment]
Yeah I checked it too, script looks simple and I dont see how it could work bad.
