### ISSUE TITLE
Add commands to Discord bot

### ISSUE THREAD

**Issue by JarnoVgr** [JarnoVgr/Mr.Green-MTA-Resources#223]
Unsure whether it's better to integrate in Lua scripts or the NodeJS apps. Probably Lua because the MTA server is aware of all the data and the nodejs app is just a gateway.

Commands examples: !players !seen !admins

**Comment by Necktrox** [comment]
Look into `discord-events` [here](https://github.com/JarnoVgr/Mr.Green-MTA-Resources/blob/master/resources/%5Bmisc%5D/%5Bdiscord%5D/discord-events/events.lua#L83).
There is an event trigger for the command packet and the `author` table contains the user roles from Discord.  See [TextCommandPacket.js](https://github.com/Necktrox/mta-discord-bot/blob/master/src/library/packets/TextCommandPacket.js) for more information. You can check if a player has a certain role for access control. `payload.author.roles` is a string list of the role names of the user on Discord.

**Comment by JarnoVgr** [comment]
Great info @Necktrox . Will look into it.
Thanks for providing your Discord resources open-source! :+1:
