### ISSUE TITLE
some maps on race not giving the full GCs

### ISSUE THREAD

**Issue by f1madkiller** [JarnoVgr/Mr.Green-MTA-Resources#257]
Hipnoze

Speedbowl (3laps) 

those 2 maps on race are not giving the correct ammount of GCs when finishing

**Comment by f1madkiller** [comment]
@Bierbuikje or @BlueYoshi97 can you check this when you guys get 2 mins

**Comment by Bierbuikje** [comment]
For Hipnoze I got 15gc as winner, the toptime was a little more than 3 minutes. In speedbowl Moshpit got 10gc, the toptime was about 2 minute 11 seconds.

If I recalculate the gc with the script as is stated here: [https://github.com/JarnoVgr/Mr.Green-MTA-Resources/blob/master/resources/%5Bgameplay%5D/gc/gc_rewards.lua#L207](url) in the gc resource I get a number of 15gc for Hipnoze and 10.9gc for Speedbowl. So there is nothing wrong with the outputs. Only thing you can do is argue that the reward for finishing is too low.

**Comment by f1madkiller** [comment]
That is yoshis terriotry then as I got a few complaints mainly from grander ty for looking into it bier
