### ISSUE TITLE
Dynamic limit for max players / slots

### ISSUE THREAD

**Issue by JarnoVgr** [JarnoVgr/Mr.Green-MTA-Resources#294]
Is it possible to increase the max players / slots amount on the fly? For example, when only 20 players are playing, set the max to 30. (Or at least, make it display like that in the server browser)

**Comment by JarnoVgr** [comment]
Seems like it's possible to do so. I'll write a resource for it.

https://wiki.multitheftauto.com/wiki/SetMaxPlayers

**Comment by EsDeKa** [comment]
@JarnoVgr I added it for you to the joinquit resource since it's really small
Interesting idea btw
