### ISSUE TITLE
Use new login API instead of forums database check

### ISSUE THREAD

**Issue by JarnoVgr** [JarnoVgr/Mr.Green-MTA-Resources#3]
Really want to get rid of manual forums database check.

**Comment by EsDeKa** [comment]
I've been trying [with fetchRemote](https://wiki.multitheftauto.com/wiki/FetchRemote) but something keeps going wrong:

    /srun url = 'http://api.mrgreengaming.com:8080/account/login'
    /srun post="user=SDK&password=______"
    /srun fetchRemote(url, function(r,e) outputConsole('JSON: ' .. r) outputConsole('Errno: ' .. e) end, post)
Result:

    JSON: {"error":2,"errorMessage":"Unknown forum user/email"}
    Errno: 0
Tried with email etc, always get error 2
Can you check for me what I'm missing @JarnoVgr ?

**Comment by AleksCore** [comment]
Will we able to make registration in-game instead of hard registration on forums? What's this API actually for?

**Comment by JarnoVgr** [comment]
Fixed!
