### ISSUE TITLE
[MODS] /votekick is bugged

### ISSUE THREAD

**Issue by Santiii727** [JarnoVgr/Mr.Green-MTA-Resources#313]
Votekick started by -]alw[-Santiii733.
Vote ended! [Yes]
And not kicked me.
Yesterday, i wanted to do the same with one who had lag in dd, but it does not work.

**Comment by EsDeKa** [comment]
Fixed in https://github.com/JarnoVgr/Mr.Green-MTA-Resources/commit/e19a8d8e874df9c9d7e9441e3544b0f30f798122
