### ISSUE TITLE
Remove vehicle speed limit

### ISSUE THREAD

**Issue by JarnoVgr** [JarnoVgr/Mr.Green-MTA-Resources#330]
See `extraairresistance` on https://wiki.multitheftauto.com/wiki/SetWorldSpecialPropertyEnabled

**Comment by Bierbuikje** [comment]
I would not be in favor to implement this server wide. If we enable this for all maps a lot of tops would be beaten because they were set under worse conditions. I think this resistance and 'slow roads' in san andreas give an extra dimension in terms of race strategies and nitro management.

**Comment by JarnoVgr** [comment]
Makes sense. Closing this for now.
