### ISSUE TITLE
Remove IRC resource

### ISSUE THREAD

**Issue by JarnoVgr** [JarnoVgr/Mr.Green-MTA-Resources#359]
Is anyone still using the IRC bots? If not, we should consider removing it to improve overall 
server performance.

**Comment by JarnoVgr** [comment]
@EsDeKa @Bierbuikje Thoughts?

**Comment by Bierbuikje** [comment]
If it improves the server we should do it, it is rarely used since we have the discord bots.

**Comment by AleksCore** [comment]
If it "eats" a lot of performance then yeah it should be removed. Anyways no one using it I guess

**Comment by EsDeKa** [comment]
Actually the discord resource is using the irc resource for its commands,
so it can't really be removed until the commands are moved to discord then

**Comment by AleksCore** [comment]
Oops

**Comment by JarnoVgr** [comment]
Wait what. That wasn't something I'd expect.

I've made #361
