### ISSUE TITLE
HD radar unnecessary resources?

### ISSUE THREAD

**Issue by JarnoVgr** [JarnoVgr/Mr.Green-MTA-Resources#40]
The @AleksCore commit that introduced the HD radar also contain icons from the singleplayer game. This should be removed if they're downloaded to clients in order to save MBs.

**Comment by EsDeKa** [comment]
One step ahead of you ^^
https://github.com/JarnoVgr/Mr.Green-MTA-Resources/commit/76f386dea27d1fd847535187c18208eec1b2fccb
