### ISSUE TITLE
Login API bug?

### ISSUE THREAD

**Issue by AleksCore** [JarnoVgr/Mr.Green-MTA-Resources#49]
Players have problems with activation and logging in.

[This guy](http://mrgreengaming.com/forums/user/11779-zaxer/) have ~700 GC as we can see and when he logging in ingame - it show 0 gc (AFAIK, didn't talked with him personally)

[This](http://mrgreengaming.com/forums/user/21006-shift-32/) and [this](http://mrgreengaming.com/forums/user/21004-eidolon/)  guys can't activate their accounts. Maybe they simply didn't activated them, but they was noticed how to do this. 

I can't be sure that they do always right, but anyways I think you should be noticed. It could be because of new login API.

**Comment by JarnoVgr** [comment]
The GC issue can't be related to the new login API. GCs are still directly retrieved from the database.

And what do you mean with 'can't active their accounts'? Can't they validate their forums account by email? (first one already works now) Or do they receive an error when logging in ingame?

**Comment by AleksCore** [comment]
I don't have enough information yet, but it seems like many people have some problems. Sadly I can't provide more information.

**Comment by JarnoVgr** [comment]
Does this still happen?

**Comment by EsDeKa** [comment]
Going to close it for now, reopen if it happens again
