### ISSUE TITLE
Add ability to mark player as lagger

### ISSUE THREAD

**Issue by BobT123** [JarnoVgr/Mr.Green-MTA-Resources#54]
Add ability to mark player as lagger, for those who have unstable ping but won't hit high enough to be kicked.

**Comment by Megas97** [comment]
A few days ago, DonGato had 100% GM on a non- gm map. And he just went through me and won. His ping was 200+ but I didn't see him lag or teleport, hmm. He just had gm on and I didn't know it cuz collisionless mode isn't seen visually until the guy goes through you.

**Comment by AfuSensi** [comment]
Add them to /blocker seems like the simplest solution.
