### ISSUE TITLE
404 not found error top left

### ISSUE THREAD

**Issue by EsDeKa** [JarnoVgr/Mr.Green-MTA-Resources#71]
Me and some other players are seeing this on both servers, probably related to some kind of website content
![](http://i.imgur.com/rUB7TkT.jpg)

**Comment by JarnoVgr** [comment]
Maybe use Wireshark to check the URL that's being requested?

**Comment by AleksCore** [comment]
Fixed in a294119e3e92cb690f02d594499faa9c9a5adc49

**Comment by AleksCore** [comment]
cabad7bad35779120492fd430d7fc3df6a39fbe0

**Comment by AfuSensi** [comment]
Thanks, that was it lol.
