### ISSUE TITLE
Use github changelog instead of outdated svn one

### ISSUE THREAD

**Issue by JarnoVgr** [JarnoVgr/Mr.Green-MTA-Resources#74]
This XML feed could be used: https://github.com/JarnoVgr/Mr.Green-MTA-Resources/commits/master.atom

**Comment by AleksCore** [comment]
Tryed to do fetchRemote from "https://github.com/JarnoVgr/Mr.Green-MTA-Resources/commits/master.atom/" - got 404 error. RIP. Also https supported only in mta 1.5.2

**Comment by AleksCore** [comment]
@Ywa, need to update MTA servers, because HTTPS supported only in MTA 1.5.2. Script is ready-to-upload, so this issue kinda solved.

**Comment by JarnoVgr** [comment]
Updated both servers to latest 1.5.2 nightly.

**Comment by AleksCore** [comment]
Great! 6231a780cea51ca6ade6f6cb8894f0df68ac1cae
