### ISSUE TITLE
Bug with nitro

### ISSUE THREAD

**Issue by AleksCore** [JarnoVgr/Mr.Green-MTA-Resources#90]
Nitro (nfs style) simply don't work sometimes. This bug is pretty random, happens very rarely for me. For some people it happens very often. 

Can't provide more info yet.

**Comment by AleksCore** [comment]
Seems like it was fixed after restarting race_fix, not sure

**Comment by JarnoVgr** [comment]
Will close for now. Re-open if it's not fixed.
