### ISSUE TITLE
Debugging (maptools resource)

### ISSUE THREAD

**Issue by AleksCore** [JarnoVgr/Mr.Green-MTA-Resources#93]
Maptools resource has minor warnings in debug, but the weird thing about it is that debug shows us the wrong line number which makes debugging impossible.

So the question is: how it's even possible and how to fix?

P.S. 
As we can see debugger points us the line 361.
![](http://i.imgur.com/G5fJSdj.png)

Line 361 is empty.
![](http://i.imgur.com/PvmJE70.png)

**Comment by AfuSensi** [comment]
Ignore it, was working on it and disabled the feature. Once I get back it will be gone.
