### ISSUE TITLE
Spikes on RM maps

### ISSUE THREAD

**Issue by f1madkiller** [JarnoVgr/Mr.Green-MTA-Resources#98]
Spikes on RM maps do not work, not a major issue but on some DDs it would be handy to have them, if Aleks or some 1 can fix it please

**Comment by AfuSensi** [comment]
Used to work, but somehow the mta update messed it up. Ill just steal alekscore's script if he lets me.

**Comment by AleksCore** [comment]
Sure I let you

**Comment by EsDeKa** [comment]
woops thought that you meant aleks' resource

**Comment by f1madkiller** [comment]
Any updates on this?

**Comment by AleksCore** [comment]
Don't really want to touch the code by @AfuSensi . Code looks large and complex for reading to me.

**Comment by f1madkiller** [comment]
Bier and I fixed it @EsDeKa can you accept Biers PR I did the fix (copyed aleks script) and bier tested and did PR
